server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://119.91.231.127:3306/cinema_database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 198170xiejun1981
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    redis:
      host: 119.91.231.127
      port: 6379
      password: xiejun198170
      database: 0

app:
  jwt:
    issuer: security-demo
    access-token-ttl: 15m
    refresh-token-ttl: 7d
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_BYTES_MIN_CHANGE_ME"

mybatis-plus:
  type-aliases-package: com.liu.entity.User # ?????
  mapper-locations: "classpath:/mapper/**/*.xml" # Mapper.xml?????????mapper??????xml???????
  configuration:
    map-underscore-to-camel-case: true # ?????????????
    cache-enabled: false # ????????
  global-config:
    db-config:
      id-type: assign_id # id???????
      update-strategy: not_null # ????????????
